export const REQUEST_NAMES = {
  LOGIN: 'LOGIN',
  FETCH_ME: 'FETCH_ME',
  FETCH_MY_TEAM: 'FETCH_MY_TEAM',
  SET_MY_TEAM: 'SET_MY_TEAM',
  UPLOAD_PUZZLE_PHOTO: 'UPLOAD_PUZZLE_PHOTO',
  FETFH_PHOTO_TASKS: 'FETFH_PHOTO_TASKS'
};
